/** Central paths for UI icons — no emoji in the game UI. */
export const UI = {
  blossom: "/icons/icon-blossom.png",
  heart: "/icons/icon-heart.png",
  dna: "/icons/dna.png",
  gemEpic: "/icons/icon-gem-epic.png",
  cosmic: "/icons/icon-cosmic-star.png",
  energy: "/icon-energy.png",
  egg: "/icons/egg.png",
  coin: "/icons/coin.png",
  crown: "/icons/icon-crown.png",
  gift: "/icons/icon-gift.png",
  lock: "/icons/icon-lock.png",
  trophy: "/icons/icon-trophy.png",
  flame: "/icons/icon-flame.png",
  sword: "/icons/icon-sword.png",
  shield: "/icons/item-shield.png",
  search: "/icons/icon-search.png",
  trash: "/icons/icon-trash.png",
  clover: "/icons/item-clover.png",
  orb: "/icons/item-orb.png",
  rage: "/icons/item-rage.png",
  nursery: "/icon-nursery.png",
  shrine: "/icon-shrine.png",
  market: "/icon-market.png",
  empire: "/icon-empire.png",
  collection: "/icon-collection.png",
  arena: "/icon-arena.png",
  home: "/icon-home.png",
  sprout: "/sprites/plant.png",
  paw: "/sprites/beast.png",
  victory: "/icons/icon-trophy.png",
  defeat: "/icons/icon-trash.png",
  boost: "/icons/item-orb.png",
  skill: "/icons/item-orb.png",
  potion: "/icons/item-orb.png",
  crate: "/icons/icon-gift.png",
  meat: "/icons/icon-flame.png",
  pearl: "/icons/item-orb.png",
  sun: "/icons/icon-cosmic-star.png",
  ship: "/icon-market.png",
  flag: "/icon-empire.png",
  candle: "/icons/icon-flame.png",
  check: "/icons/icon-cosmic-star.png",
} as const;

export type UiIconPath = (typeof UI)[keyof typeof UI];
